// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYTFkX86jhbMuQ1VNZomNbDUEUPziYSI',
    appId: '1:1027188643153:web:ce0070f743cdcb02afaf70',
    messagingSenderId: '1027188643153',
    projectId: 'rideroster-2030d',
    authDomain: 'rideroster-2030d.firebaseapp.com',
    storageBucket: 'rideroster-2030d.firebasestorage.app',
    measurementId: 'G-W70V7NRFQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPcnxbe8ky8hj8fzBFjLWokI5XLah-6Y',
    appId: '1:1027188643153:android:e94589c8d1b7f066afaf70',
    messagingSenderId: '1027188643153',
    projectId: 'rideroster-2030d',
    storageBucket: 'rideroster-2030d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1mr045KNUmZHYC48OtQFDGpr83J7sJbk',
    appId: '1:1027188643153:ios:6f7f7ff704422955afaf70',
    messagingSenderId: '1027188643153',
    projectId: 'rideroster-2030d',
    storageBucket: 'rideroster-2030d.firebasestorage.app',
    iosBundleId: 'com.example.rideroster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1mr045KNUmZHYC48OtQFDGpr83J7sJbk',
    appId: '1:1027188643153:ios:6f7f7ff704422955afaf70',
    messagingSenderId: '1027188643153',
    projectId: 'rideroster-2030d',
    storageBucket: 'rideroster-2030d.firebasestorage.app',
    iosBundleId: 'com.example.rideroster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoYTFkX86jhbMuQ1VNZomNbDUEUPziYSI',
    appId: '1:1027188643153:web:a051d41dc7be25e4afaf70',
    messagingSenderId: '1027188643153',
    projectId: 'rideroster-2030d',
    authDomain: 'rideroster-2030d.firebaseapp.com',
    storageBucket: 'rideroster-2030d.firebasestorage.app',
    measurementId: 'G-G92Q06FVXQ',
  );
}
